### Cria usuário e mostra token como resposta

POST http://localhost:3000/user/signup
Content-Type:  application/json


{
	"email": "panificadoraalpha@gmail.com",
	"password": "chegamantegaderrete"
}

### verifica login e  mostra token como resposta

POST http://localhost:3000/user/login
Content-Type:  application/json


{
	"email": "panificadoraalpha@gmail.com",
	"password": "chegamantegaderrete"
}


### retorna as informações do usuário logado

GET http://localhost:3000/user/profile
Content-Type:  application/json
authorization: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTE2MjgzMzAsImV4cCI6MTYxMTYyODM5MH0.Rh3VeOFpLejjobhfJ24afTeTQlnvpNU_81pZ1XxdPGE'
}
